name: Azure ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # Your Azure Service Principal credentials

    - name: Install Azure ML extension
      run: |
        az extension add -n ml -y

    - name: Submit Azure ML Job
      run: |
        az ml job create --file src/job.yml --resource-group challenge-amit --workspace-name development-ml
      env:
        AZURE_ML_SUBSCRIPTION: ${{ secrets.AZURE_ML_SUBSCRIPTION }}
